// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using EmpleadosCrud.Entities.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace EmpleadosCrud.DataAccess.Context
{
    public partial class TareacrudempleadoContext : DbContext
    {
        public TareacrudempleadoContext()
        {
        }

        public TareacrudempleadoContext(DbContextOptions<TareacrudempleadoContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tbEmpleados> tbEmpleados { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS");

            modelBuilder.Entity<tbEmpleados>(entity =>
            {
                entity.HasKey(e => e.empe_Id)
                    .HasName("PK_tbEmpleados_empe_Id");

                entity.Property(e => e.empe_Apellidos).HasMaxLength(150);

                entity.Property(e => e.empe_Nombres).HasMaxLength(150);

                entity.Property(e => e.empe_Sexo)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.empe_Telefono).HasMaxLength(15);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}