// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace EmpleadosCrud.WebUI.Entities
{
    public partial class tbEmpleados
    {
        public int empe_Id { get; set; }
        public string empe_Nombres { get; set; }
        public string empe_Apellidos { get; set; }
        public string empe_Sexo { get; set; }
        public string empe_Telefono { get; set; }
    }
}